### ISSUE TITLE
Textual serialisation format could be more concise

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emf-cbp#3]
I don't think that square brackets are necessary:

```
create EPackage
create EClass
create EClass
add eClassifiers 1 2 3 // Add the two EClasses under the 
                       // eClassifiers feature of the EPackage
```
For internal object IDs we can use numbers (as we already do), and for external object IDs (cross-resource references), we could use strings e.g.

```
add eSuperTypes 2 3 "foo.ecore/ExternalClass1"
```
For efficiency we could keep track of external resources in the same way as EPackages to avoid from referring to complete filenames every time e.g.

```
resource "foo.ecore"
addSuperTypes 2 3 1#"ExternalClass1" // #1 refers to the first external resource i.e. foo.ecore
```

**Comment by wrwei** [comment]
OK changed the implementation so that we do not need square brackets now, altered all tests accordingly, all passed

**Comment by kolovos** [comment]
Running the following EOL script against an empty CBP textual resource

```
var p = new EPackage;
p.name = "tree";

var tree = new EClass;
tree.name = "Tree";

p.eClassifiers.add(tree);
```

produces the text below - note markers in [] on lines 3 and 4

```
CBP_TEXT 1.0
REGISTER_EPACKAGE http://www.eclipse.org/emf/2002/Ecore
CREATE_AND_ADD_TO_RESOURCE ecore-EPackage 0 [1]
CREATE_AND_SET_EREFERENCE 0 ecore-EPackage-eFactoryInstance ecore-EFactory 1 [2]
SET_EREFERENCE 1 ecore-EFactory-ePackage 0
SET_EATTRIBUTE_PRIMITIVE 0 ecore-EPackage-name tree
CREATE_AND_ADD_TO_RESOURCE ecore-EClass 2
SET_EATTRIBUTE_PRIMITIVE 2 ecore-EClass-name Tree
SET_EREFERENCE 2 ecore-EClass-ePackage 0
SET_EATTRIBUTE_PRIMITIVE 0 ecore-EPackage-name tree
SET_EREFERENCE 0 ecore-EPackage-eFactoryInstance 1
ADD_TO_EREFERENCE 0 ecore-EPackage-eClassifiers 2
REMOVE_FROM_RESOURCE 2
ADD_TO_EREFERENCE 0 ecore-EPackage-eClassifiers 2
SET_EATTRIBUTE_PRIMITIVE 2 ecore-EClass-name Tree
SET_EREFERENCE 2 ecore-EClass-ePackage 0
```

[1] So far we only have 1 registered EPackage in the resource (http://www.eclipse.org/emf/2002/Ecore). As such, we should only need "EPackage" instead of "ecore-EPackage" to uniquely identify the type of the new element. Also, we don't need to save the index of the new EPackage (0) as we can recompute it when we load the resource.

[2] We already know the type of 0 (EPackage) so we don't need the fully qualified name "ecore-EPackage-eFactoryInstance" to uniquely identify the name of the feature set. "eFactoryInstance" would suffice.

**Comment by agarciadom** [comment]
Just to keep track of our discussion on Skype today - we need to keep separate two concepts:
* A format based on names is more resilient against metamodel evolution.
* Having redundant information can be useful for debugging CBP itself.

Therefore, we decided to allow for multiple file extensions that implement these combinations:
* `.cbptext` = ID-based, no debugging
* `.cbptextd` = ID-based, debugging
* `.cpbtextn` = name-based, no debugging
* `.cbptextnd` = name-based, debugging

To keep the parsers as simple as possible, the debugging info could be provided as comments. These could be as simple as "from # to end of line":

```
CREATE_AND_ADD_TO_RESOURCE EPackage # object 0
```

Another idea is to generalize the `CBP*ResourceImpl` classes to a CBPResourceImpl that uses composition instead of inheritance to plug the proper deserializer and serializer. This should also allow for specifying actions in different ways: numbers, short commands, longer commands...

**Comment by kolovos** [comment]
The textual serialisation format has been retired (at least for now)
